name: CodeNotary

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@master

     - name: Verify
       uses: vchain-us/verify-action@master
       with:
         signerID: 9e5f5f79-cb69-4d30-9b77-1feced3892df
